---
- name: Deploy servers 
  hosts: webservers
  remote_user: root
  become: true

  tasks:

    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Backup httpd.conf
      command: cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.bak

    - name: Copy new http.conf
      copy:
        src: ./httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: ugo+rw

    - name: Create content
      copy:
        content: "Hello World from {{ansible_hostname}}"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: ugo+rw

    - name: Enable firewall
      firewalld:
        port: 8080/tcp
        state: enabled
        immediate: yes
        permanent: yes
             
    - name: Restart firewall
      service: 
        name: firewalld
        state: restarted
    
    - name: Start server
      service:
        name: httpd
        state: restarted
        enabled: true 

