---
- hosts: webservers
  tasks:
    - name: Update
      yum: name=epel-release
    - name: Install 
      yum: name=nginx state=latest
      changed_when: true
      notify:
        - Start
    - name: Create www directory
      file:
        path: /var/www/shannonphu-helloworld.com
        state: directory
        mode: 0775
        owner: root
        group: root
    - name: Delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload
    - name: Create folder for nginx conf
      file:
        path: /etc/nginx/sites-enabled
        state: directory
        owner: root
        group: root
        mode: 0775
    - name: Copy site.conf
      copy:
        src: site.conf.j2
        dest: /etc/nginx/sites-enabled/shannonphu-helloworld.com
        owner: root
        group: root
        mode: 0644
      changed_when: true
      notify: 
        - Reload
  handlers:
    - name: Start
      service: name=nginx state=started
    - name: Reload
      service: name=nginx state=reloaded
