---
- name: Configure servers 
  hosts: webservers
  remote_user: root
  become: true

  tasks:

    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Create content
      copy:
        content: "Hello from shannon"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: ugo+rw

    - name: Enable firewall
      firewalld:
        service: httpd
        state: enabled
        immediate: yes
        permanent: yes
      ignore_errors: yes         

    - name: Start server
      service:
        name: httpd
        state: started
        enabled: true 

