-
    name: Executing ansible playbook on target System Deploy/Cleanup/Start/Stop Server
    hosts: webservers
    become: yes
    vars:
        ansible_become_pass: 'C1sco12345'
    tasks:
        -   name: Ping all servers to check if they are reachable
            ping:
            tags: setup

        -   name: Install apache web server
            yum:
                name: httpd
                state: present
            tags: setup

        -   name: Change HTTPD port Number
            lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
            tags: setup

        -   name: Start service httpd
            service:
                name: httpd
                state: started
            tags: 
                -   setup
                -   startServer

        -   name: Create content
            copy:
                content: "<h1>Hello World from {{ansible_hostname}}</h1>"
                dest: /var/www/html/index.html
                owner: root
                group: root
                mode: ugo+rw
            tags: setup

        -   name: Enable firewall port for external access
            firewalld:
                port: 8080/tcp
                permanent: yes
                state: enabled
            tags: setup

        -   name: Reload firewall for the effect to take place
            command: 'firewall-cmd --reload'
            tags: setup

        -   name: Stop Apache web server
            service:
                name: httpd
                state: stopped
                enabled: false 
            tags:
                -   cleanup
                -   stopServer

        -   name: Remove Apache Package
            yum:
                 name: httpd
                 state: absent
            tags: cleanup

        -   name: Removing the files created on CentOS1 & CentOS2
            file:
                state: absent
                path: /var/www/html/index.html
            tags: cleanup

        -   name: Disable firewall
            firewalld:
                port: 8080/tcp
                immediate: yes
                permanent: yes
                state: disabled
            tags: cleanup
            
              
              
